# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
username: "framrecruit@gmail.com"
password: "framgiavn"
GOOGLE_OAUTH2_APP_ID: "890165441453-es1u1msajfv6lv7t6mg4l3pe3pbuk9o0.apps.googleusercontent.com"
GOOGLE_OAUTH2_APP_SECRET: "GEpSLbWTonkbvQf3wcWfErli"
FACEBOOK_APP_ID: "807623896098872"
FACEBOOK_APP_SECRET: "b0e27f408dca25c29acdcd1f6916851e"
LINKEDIN_APP_ID: "8140laq58tusjl"
LINKEDIN_APP_SECRET: "eQw8Jz7EW7cYmycL"
